name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: mkdir ${{ github.workspace }}/docs
      - name: Generate documentation
        uses: swiftdocorg/swift-doc@master
        with:
          inputs: "Sources/"
          output: "docs/"
      - run: sudo chmod -R 0755 docs/
      - name: Upload Documentation to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: "${{ github.actor }}@users.noreply.github.com"
          ACTION_NAME: "${{ github.actor }}"
          GH_PAT: ${{ secrets.GH_PAT }}
          MD_FOLDER: docs
          OWNER: Flight-School
          REPO_NAME: Money
          SKIP_MD: README.md
